#########################################################################
# Title:         Cloudbox: Plex Plugins / Trakt.tv                      #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check to see if {{ plex_name | title }} is running
  block:

  - name: Gather list of running Docker containers
    shell: "docker ps --format '{{ '{{' }} .Names{{ '}}' }}' | xargs echo -n"
    register: docker_running_containers_list

  - name: Set 'docker_running_containers_list' variable
    set_fact:
      docker_running_containers_list: "{{ (docker_running_containers_list.stdout).split() }}"

  - name: Stop {{ plex_name | title }} container
    docker_container:
      name: "{{ plex_docker_container }}"
      state: stopped
    when: (plex_docker_container in docker_running_containers_list)

  when: ('plex-plugin-trakttv' in ansible_run_tags)

- name: Remove Previous Trakt.tv Plugin
  file:
    path: "{{ plex_plugin_trakttv_paths_location }}"
    state: absent

- name: "Create {{ plex_name | title }} 'plug-ins' directory"
  file: "path={{ item }} state=directory owner={{ user.name }} group={{ user.name }} mode=0775 recurse=yes"
  with_items:
    - "{{ plex_paths_plugins_location }}"

- name: Install Trakt.tv Plugin
  unarchive:
    src: "{{ plex_plugin_trakttv_release_url }}"
    dest: "{{ plex_paths_plugins_location }}"
    copy: no
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    validate_certs: no
  register: plex_plugin_trakttv_download_status
  ignore_errors: yes

- name: Post-Unsuccessfull Trakt.tv Plugin Install
  debug:
    msg: "Trakt.tv Plugin install failed."
  when: (plex_plugin_trakttv_download_status is failed)

- name: Start {{ plex_name | title }} container
  docker_container:
    name: "{{ plex_docker_container }}"
    state: "{{ plex_docker_state }}"
  when:
    - ('plex-plugin-trakttv' in ansible_run_tags)
    - (plex_docker_container in docker_running_containers_list)
